config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root "welcome#index"

  #잘못된 경로로 요청이 오면, 무시해버린다.
  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      :validate => true
	attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,   :validate => true
	attribute :nickname,  :captcha  => true

	def headers 
		{
		  	:subject => "포트폴리오 사이트에서 보낸 문의 메일입니다.",
		  	:to => "sangjunpark0203@gmail.com",
		  	:from => %("#{name}" <#{email}>)
		}
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/project.rb
class Project < ActiveRecord::Base
	extend FriendlyId
  	friendly_id :title, use: :slugged

  	has_attached_file :image
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable
  #:registerable 을 주석처리하지 않으면, 회원가입이 가능하다.
  #이 웹 페이지는 모든 유저가 동등한 권한을 갖고 있기 때문에 회원가입을 제한한다.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end

	def create
		@contact = Contact.new(params[:contact])
	    @contact.request = request
	    if @contact.deliver
	      flash.now[:error] = nil
	    else
	      flash.now[:error] = '오류가 발생하여 이메일을 보낼 수 없습니다. sangjunpark0203@gmail.com 로 문의주세요.'
	      render :new
	    end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	#index, show 페이지는 볼 수 있다.
	before_action :authenticate_user!, except: [:index, :show]

	def index
		#현재 두페이지만 하려면 per_page: 2 로 설정하면 된다.
		@posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new post_params

		if @post.save
			redirect_to @post, notice: "정상적으로 저장되었습니다."
		else
			render 'new', notice: "비정상 저장 오류입니다."
		end
	end

	def show

	end

	def edit
	end

	def update
		if @post.update post_params
			redirect_to @post, notice: "정상적으로 저장되었습니다."
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :slug, :image)
	end

	def find_post
		@post = Post.friendly.find(params[:id])
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	#index, show 페이지는 볼 수 있다.
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@projects = Project.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params

		if @project.save
			redirect_to @project, notice: "프로젝트가 정상적으로 생성되었습니다."
		else
			render 'new'
		end
	end

	def show

	end

	def edit
	end

	def update
		if @project.update project_params
			redirect_to @project, notice: "정상적으로 프로젝트가 수정되었습니다."
		else
			render 'edir'
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_path
	end

	private

	def find_project
		@project = Project.friendly.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug, :image)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		#최근에 작성된 5개의 글만 보여주도록 제한합니다.
		@posts = Post.all.limit(7).order("created_at desc")
		@projects = Project.all.limit(7).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	#Redcarpet 을 상속하여 highlight 효과를 주기 위한 조치
	class HTMLwithPygments < Redcarpet::Render::HTML
	    def block_code(code, language)
	      Pygments.highlight(code, lexer: language)
	    end
  	end

	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true,
			strikethrough: true,
			highlight: true,
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">이메일 전송 완료</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>이메일이 성공적으로 전송되었습니다.</h1>
	<p>Sendgrid starter를 사용하고 있어서, 전송까지 약 5분정도 소요됩니다.</p>
	<p>이메일을 받는대로 되도록 빠른 시일내에 답변을 드리겠습니다.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">문의하기</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name, "이름" %><br>
		<%= f.text_field :name, required: true, :placeholder => "이름을 입력해주세요. (예) Sangjun Park" %>

		<br>

		<%= f.label :email, "이메일" %><br>
		<%= f.email_field :email, required: true, :placeholder => "이메일을 입력해주세요. (예) junee01@gmail.com" %>

		<br>

		<%= f.label :message, "내용" %><br>
		<%= f.text_area :message, as: :text, :placeholder => "내용을 입력해주세요. (예) 당신을 채용하고 싶습니다." %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'leave this field blank' %>
		</div>

		<%= f.submit '이메일 전송하기', class: "button" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Portfolio Web page for Junee01</title>
	<%# links for bootstrap, googlefont %>
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>

	<%# 깃헙 모양의 파비콘 표시 %>
	<%= favicon_link_tag 'github.ico', type: 'image/ico' %>
</head>
<body>
	<%# header part %>
	<header id="main_navigation" class="clearfix">
		<%= link_to "Portfolio & Junee01", root_path, class: "name" %>
		<nav>
			<%= link_to "이력서", post_path("95f3fb02-5d36-4e3d-a837-fa842696e184") %>
			<%= link_to "오픈소스", posts_path %>
			<%= link_to "프로젝트", projects_path %>
			<%= link_to "문의하기", new_contact_path %>
			<% if user_signed_in? %>
				<%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
			<% else %>
				<%= link_to "로그인", new_user_session_path %>
			<% end %>
		</nav>
	</header>
	<%# header part end %>

	<%# 경고 메시지가 뜨면 보여준다는 의미 %>
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% elsif alert %>
       <p class="alert"><%= alert %></p>
 	<% end %>

	<%# 실제 내용들을 partial 로 가져올 부분이다. %>
	<%= yield %>
	<%# footer part %>
	<footer id="main_footer">
		<p class="copyright">
			&copy 2016 Sangjun Park(Junee01)
			<nav>
				<a href="https://www.instagram.com/junee.junee/" target="_blank"><i class="fa fa-instagram"></i></a>
				<a href="https://www.facebook.com/sangjun.park.370" target="_blank"><i class="fa fa-facebook"></i></a>
				<a href="https://github.com/Junee01" target="_blank"><i class="fa fa-github"></i></a>
				<a href="http://blog.naver.com/potter777777" target="_blank"><i class="fa fa-pencil-square-o"></i></a>
				<a href="https://www.youtube.com/channel/UCTUZQ9-qHWxkXJ9QsuKG4Ig" target="_blank"><i class="fa fa-youtube"></i></a>
			</nav>
		</p>
	</fotter>
	<%# footer part end %>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'portfolio-junee01';
    var disqus_identifier = '<%= @post.id %>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');

    s.src = '//portfolio-junee01.disqus.com/embed.js';

    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving: </h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title, "이름" %><br>
	<%= f.text_field :title, :placeholder => "포스트 제목을 입력해주세요." %>

	<br><br>

	<%= f.label :content, "내용" %><br>
	<%= f.text_area :content, :placeholder => "포스트할 내용을 입력해주세요." %>

	<br><br>

	<%# 이미지 넣는 부분입니다. %>
 	<%= f.file_field :image %>

 	<br><br><br>

	<%= f.submit "포스팅 생성" %>



<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">포스트 수정하기</h1>

<div class="skinny_wrapper wrapper_padding">

<%= render 'form' %>

</div>

app/views/posts/index.html.erb
<h1 id="page_title">오픈소스 활동</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @posts.each do |post| %>
		<%# 제목이 "Resume with Markdown"인 포스트는 목록에 보여주지 않는다. %>
		<% if post.title == "Resume with Markdown" || post.title == "이력서" %>
		<% next %>
		<% end %>
		<div class="post">
			<%# 작성일을 기준으로 얼마나 지났는지 확인하여 보여준다. %>
			<p class="date"><%= post.created_at.strftime('%A, %B %d') %></p>
			<h2><a href="#"><%= link_to post.title, post %></a></h2>
			<hr>
		</div>
	<% end %>

	<%# 로그인한 사람만 새로운 포스팅을 할 수 있다. %>
	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "새로운 포스팅 하기", new_post_path %>
		</div>
	<% end %>
</div>

<%# pagination function %>
<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">새로운 포스팅하기</h1>

<div class="skinny_wrapper wrapper_padding">

<%= render 'form' %>

</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @post.created_at.strftime('%A, %B %d') %></p>
		<h2><%= @post.title %></h2>
		<hr>
	</header>

	<div id="content">

		<%# 포스팅에 관한 이미지 %>
		<%# 만약에 이미지가 없다면 넘어가고, 있다면 보여줍니다. %>
		<div class="content_image">
			<% if @post.image.file? %>
				<%= image_tag @post.image.url %>
				<hr>
			<% else %>
				<%# skip %>
			<% end %>
		</div>

		<%# content 내용을 markdown 을 이용하여 특수효과를 넣어 보여준다. %>
		<%= markdown @post.content %>
		
		<%# 이력서 페이지는 Show 페이지가 다르게 표시됩니다. 끝 부분에 서로로 연결되는 버튼이 추가됩니다. %>
		<% if @post.title == "이력서" %>
			<div class="button_wrapper">
				<%= link_to "영문 이력서 보기", post_path("resume"), :class => "post_button" %>
			</div>
		<% elsif @post.title == "Resume with Markdown" %>
			<div class="button_wrapper">
				<%= link_to "한글 이력서 보기", post_path("95f3fb02-5d36-4e3d-a837-fa842696e184"), :class => "post_button" %>
			</div>
		<% end %>
	</div>

	<%# 로그인을 한 유저에게만 수정과 삭제의 권한이 주어진다. %>
	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "포스팅 추가", new_post_path %>
			<%= link_to "수정하기", edit_post_path(@post) %>
			<%= link_to "삭제하기", post_path(@post), method: :delete, data: { confirm: "정말로 삭제하시겠습니까?" } %>
		</div>
	<% end %>

	<hr>

	<%# 이력서 부분은 Disqus가 아닌 시지온의 라이브리를 적용해본다. %>
	<% if @post.title == "Resume with Markdown" || @post.title == "이력서" %>
		<!-- 라이브리 시티 설치 코드 -->
		<div id="lv-container" data-id="city" data-uid="MTAyMC8yNjY5OS8zMjg5">
			<script type="text/javascript">
		   (function(d, s) {
		       var j, e = d.getElementsByTagName(s)[0];

		       if (typeof LivereTower === 'function') { return; }

		       j = d.createElement(s);
		       j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
		       j.async = true;

		       e.parentNode.insertBefore(j, e);
		   })(document, 'script');
			</script>
		<noscript> 라이브리 댓글 작성을 위해 JavaScript를 활성화 해주세요</noscript>
		</div>
		<!-- 시티 설치 코드 끝 -->
	<% else %>
		<div id="share_box">
			<p>공유하기</p>
			<!-- Twitter 으로 공유하기 -->
			<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @sangjunpark - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
			<!-- Facebook 으로 공유하기 -->
		    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
		</div>

		<hr>

		<%= render 'disqus' %>
	<% end %>
</div>

app/views/projects/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'portfolio-junee01';
    var disqus_identifier = '<%= @project.id %>';
    var disqus_title = '<%= @project.title %>';
    var disqus_url = '<%= url_for([@project, {only_path: false}]) %>';

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');

    s.src = '//portfolio-junee01.disqus.com/embed.js';

    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/projects/_form.html.erb
<%= form_for @project, html: { multipart: true } do |f| %>
	<% if @project.errors.any? %>
		<h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving: </h2>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title, "프로젝트 주제" %><br>
	<%= f.text_field :title, :placeholder => "프로젝트 주제를 입력해주세요." %>

	<br><br>

	<%= f.label :description, "프로젝트 설명" %><br>
	<%= f.text_area :description, :placeholder => "프로젝트에 대한 설명을 기술해주세요." %>

	<br><br>

	<%= f.label :link, "프로젝트 링크(GitHub)" %><br>
	<%= f.text_field :link, :placeholder => "프로젝트에 대한 내용을 볼 수 있는 링크를 입력해주세요." %>

	<br><br>

	<%# 이미지 넣는 부분입니다. %>
 	<%= f.file_field :image %>

 	<br><br><br>

	<%= f.submit "프로젝트 생성" %>

<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">프로젝트 수정하기</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">프로젝트 자료</h1>

<div id="posts_wrapper" class="skinny_wrapper">
	<% @projects.each do |project| %>
		<div class="post">
			<p class="date"><%= project.created_at.strftime('%A, %B %d') %></p>
			<h2><a href="#"><%= link_to project.title, project %></a></h2>
			<hr>
		</div>
	<% end %>

	<%# 로그인한 유저만 새로운 글을 작성할 수 있습니다. %>
	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "프로젝트 추가하기", new_project_path %>
		</div>
	<% end %>
</div>

<%# pagination function %>
<%= will_paginate @projects %>

app/views/projects/new.html.erb
<h1 id="page_title">프로젝트 추가하기</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %B %d') %></p>
		<h2><%= @project.title %></h2>
		<hr>
	</header>

	<div id="content">

		<%# 프로젝트에 관한 이미지 %>
		<%# 만약에 이미지가 없다면 넘어가고, 있다면 보여줍니다. %>
		<div class="content_image">
			<% if @project.image.file? %>
				<%= image_tag @project.image.url %>
				<hr>
			<% else %>
				<%# skip %>
			<% end %>
		</div>
		

		<%# 프로젝트에 관한 내용을 기술하는 부분 %>
		<%= markdown @project.description %>

		<%# 프로젝트와 연결된 링크를 기술하는 부분 %>
		<div class="button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank">
				'<%= @project.title %>' (으)로 방문하기
			</a>
		</div>
	</div>

	<%# 로그인을 한 유저에게만 수정과 삭제의 권한이 주어집니다. %>
	<% if user_signed_in? %>
		<div id="admin_links">
			<%= link_to "프로젝트 추가", new_project_path %>
			<%= link_to "수정하기", edit_project_path(@project) %>
			<%= link_to "삭제하기", project_path(@project), method: :delete, data: { confirm: "Are you sure?" } %>
		</div>
	<% end %>

	<hr>

	<div id="share_box">
		<p>공유하기</p>
		<!-- Twitter 으로 공유하기 -->
		<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @project.title %> by @sangjunpark - &amp;url=<%= url_for([@project, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-twitter"></i></a>
		<!-- Facebook 으로 공유하기 -->
	    <a onclick="javascript:window.open('http://www.facebook.com/sharer.php?u=<%= url_for([@project, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fa fa-facebook"></i></a>
	</div>

	<hr>

		<%= render 'disqus' %>
		
</div>

app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
	<div class="col-1 about homepage_content">
		<h2>소개</h2>
		<hr>
		<%= image_tag 'Junee01.gif', alt: 'Junee', class: "img-circle" %>
		<br><br>
		<p><strong>이름</strong> : 박상준(Junee01)</p>
		<p><strong>전공</strong> : 컴퓨터 공학</p>
		<hr>
		<h2>보유 기술</h2>
		<ul>
			<li>C, Java, Ruby, Python 2.7, Swift</li>
			<li>HTML/CSS, JS, jQuery</li>
			<li>Rails4, django1.8, Bootstrap3, Metro</li>
			<li>SQL, MySQL, SQlite, Linux</li>
			<li>Web Scraping, Degisn Pattern</li>
			<li>Git, Aws(EC2, Beanstalk, S3)</li>
		</ul>
	</div>
	<div class="col-2 homepage_content">
		<h2>오픈소스 활동</h2>
		<hr>

		<% @posts.each do |post| %>
			<%# 제목이 "Resume with Markdown" 또는 "이력서"인 포스트는 목록에 보여주지 않는다. %>
			<% if post.title == "Resume with Markdown" || post.title == "이력서" %>
			<% next %>
			<% end %>
			<h3><a href="#"><%= link_to post.title, post %></a></h3>
			<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
		<% end %>
	</div>
	<div class="col-3 homepage_content">	
		<h2>프로젝트 모음</h2>
		<hr>

		<% @projects.each do |project| %>
			<h3><a href="#"><%= link_to project.title, project %></a></h3>
			<p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
		<% end %>
	</div>
</div>